deepspeed --hostfile ./hostfile --include=$train_CUDA_VISIBLE_DEVICES --master_addr 10.167.193.30 --master_port 29503 src/train.py \
	--stage sft \
	--model_name_or_path $MODEL_PATH \
	--do_train \
    --preprocessing_num_workers 16 \
	--dataset tmp_train \
	--template $template \
	--finetuning_type lora \
	--lora_target all \
	--output_dir $lora_output_dir \
	--overwrite_cache \
	--overwrite_output_dir \
	--per_device_train_batch_size $batch_size \
	--gradient_accumulation_steps $gradient_acc_steps \
	--flash_attn fa2 \
    --pissa_init True \
    --pissa_iter 4 \
    --pissa_convert True \
	--lr_scheduler_type cosine \
	--logging_steps 10 \
	--save_steps $save_steps \
	--cutoff_len 4096 \
    --quantization_bit 8 \
    --save_only_model True \
	--learning_rate 1e-4 \
	--num_train_epochs 5.0 \
	--plot_loss \
	--fp16 \
	--group_by_length \
	--use_fast_tokenizer False \
	--lora_alpha 16 \
	--lora_rank 8 \
	--lora_dropout 0.1


